export type FurnitureCategory =
  | "living"
  | "bedroom"
  | "kitchen"
  | "bathroom"
  | "office"
  | "storage";

export interface FurnitureItem {
  id: string;
  name: string;
  category: FurnitureCategory;
  width: number;
  depth: number;
  height: number;
  color: string;
  icon: string;
}

export const CATEGORY_LABELS: Record<FurnitureCategory, string> = {
  living: "Гостиная",
  bedroom: "Спальня",
  kitchen: "Кухня",
  bathroom: "Ванная",
  office: "Кабинет",
  storage: "Хранение",
};

export const FURNITURE_CATALOG: FurnitureItem[] = [
  {
    id: "living-sofa",
    name: "Диван",
    category: "living",
    width: 2200,
    depth: 900,
    height: 850,
    color: "#6B7B8D",
    icon: "\u{1F6CB}\uFE0F",
  },
  {
    id: "living-armchair",
    name: "Кресло",
    category: "living",
    width: 850,
    depth: 850,
    height: 850,
    color: "#7B8B6F",
    icon: "\u{1FA91}",
  },
  {
    id: "living-coffee-table",
    name: "Журнальный столик",
    category: "living",
    width: 1100,
    depth: 600,
    height: 450,
    color: "#C4A882",
    icon: "\u2615",
  },
  {
    id: "living-tv-stand",
    name: "Тумба под ТВ",
    category: "living",
    width: 1600,
    depth: 450,
    height: 500,
    color: "#8B7355",
    icon: "\u{1F4FA}",
  },
  {
    id: "living-display-cabinet",
    name: "Шкаф-витрина",
    category: "living",
    width: 800,
    depth: 400,
    height: 2000,
    color: "#A0522D",
    icon: "\u{1F5C4}\uFE0F",
  },
  {
    id: "living-bookshelf",
    name: "Книжный стеллаж",
    category: "living",
    width: 800,
    depth: 300,
    height: 1800,
    color: "#DEB887",
    icon: "\u{1F4DA}",
  },
  {
    id: "bedroom-double-bed",
    name: "Кровать двуспальная",
    category: "bedroom",
    width: 2000,
    depth: 1600,
    height: 900,
    color: "#8B7D6B",
    icon: "\u{1F6CF}\uFE0F",
  },
  {
    id: "bedroom-single-bed",
    name: "Кровать односпальная",
    category: "bedroom",
    width: 2000,
    depth: 900,
    height: 900,
    color: "#9B8B7B",
    icon: "\u{1F6CF}\uFE0F",
  },
  {
    id: "bedroom-nightstand",
    name: "Тумба прикроватная",
    category: "bedroom",
    width: 500,
    depth: 400,
    height: 550,
    color: "#A0522D",
    icon: "\u{1FAB5}",
  },
  {
    id: "bedroom-dresser",
    name: "Комод",
    category: "bedroom",
    width: 1200,
    depth: 500,
    height: 800,
    color: "#CD853F",
    icon: "\u{1F5C4}\uFE0F",
  },
  {
    id: "bedroom-wardrobe-sliding",
    name: "Шкаф-купе",
    category: "bedroom",
    width: 2400,
    depth: 600,
    height: 2400,
    color: "#8B7355",
    icon: "\u{1F454}",
  },
  {
    id: "bedroom-vanity",
    name: "Туалетный столик",
    category: "bedroom",
    width: 1000,
    depth: 450,
    height: 750,
    color: "#DEB887",
    icon: "\u{1F484}",
  },
  {
    id: "kitchen-dining-table",
    name: "Стол обеденный",
    category: "kitchen",
    width: 1400,
    depth: 800,
    height: 750,
    color: "#D2B48C",
    icon: "\u{1F37D}\uFE0F",
  },
  {
    id: "kitchen-chair",
    name: "Стул",
    category: "kitchen",
    width: 450,
    depth: 450,
    height: 900,
    color: "#CD853F",
    icon: "\u{1FA91}",
  },
  {
    id: "kitchen-lower-cabinet",
    name: "Кухонный гарнитур (нижний)",
    category: "kitchen",
    width: 2400,
    depth: 600,
    height: 850,
    color: "#F5F5DC",
    icon: "\u{1F373}",
  },
  {
    id: "kitchen-upper-cabinet",
    name: "Кухонный гарнитур (верхний)",
    category: "kitchen",
    width: 2400,
    depth: 350,
    height: 700,
    color: "#F5F5DC",
    icon: "\u{1F5C4}\uFE0F",
  },
  {
    id: "kitchen-fridge",
    name: "Холодильник",
    category: "kitchen",
    width: 600,
    depth: 650,
    height: 1800,
    color: "#C0C0C0",
    icon: "\u2744\uFE0F",
  },
  {
    id: "kitchen-stove",
    name: "Плита",
    category: "kitchen",
    width: 600,
    depth: 600,
    height: 850,
    color: "#A9A9A9",
    icon: "\u{1F525}",
  },
  {
    id: "bathroom-bathtub",
    name: "Ванна",
    category: "bathroom",
    width: 1700,
    depth: 700,
    height: 600,
    color: "#F0F8FF",
    icon: "\u{1F6C1}",
  },
  {
    id: "bathroom-shower",
    name: "Душевая кабина",
    category: "bathroom",
    width: 900,
    depth: 900,
    height: 2100,
    color: "#E0FFFF",
    icon: "\u{1F6BF}",
  },
  {
    id: "bathroom-sink",
    name: "Раковина",
    category: "bathroom",
    width: 600,
    depth: 450,
    height: 850,
    color: "#FFFAFA",
    icon: "\u{1F6B0}",
  },
  {
    id: "bathroom-toilet",
    name: "Унитаз",
    category: "bathroom",
    width: 400,
    depth: 650,
    height: 400,
    color: "#FFFFF0",
    icon: "\u{1F6BD}",
  },
  {
    id: "bathroom-washing-machine",
    name: "Стиральная машина",
    category: "bathroom",
    width: 600,
    depth: 500,
    height: 850,
    color: "#DCDCDC",
    icon: "\u{1F9FA}",
  },
  {
    id: "office-desk",
    name: "Стол рабочий",
    category: "office",
    width: 1400,
    depth: 700,
    height: 750,
    color: "#D2B48C",
    icon: "\u{1F5A5}\uFE0F",
  },
  {
    id: "office-chair",
    name: "Кресло офисное",
    category: "office",
    width: 650,
    depth: 650,
    height: 1100,
    color: "#2F4F4F",
    icon: "\u{1F4BA}",
  },
  {
    id: "office-shelf",
    name: "Стеллаж",
    category: "office",
    width: 800,
    depth: 350,
    height: 1800,
    color: "#DEB887",
    icon: "\u{1F4D6}",
  },
  {
    id: "storage-wardrobe",
    name: "Шкаф",
    category: "storage",
    width: 1200,
    depth: 600,
    height: 2200,
    color: "#8B7355",
    icon: "\u{1F6AA}",
  },
  {
    id: "storage-wall-shelf",
    name: "Полка навесная",
    category: "storage",
    width: 800,
    depth: 250,
    height: 300,
    color: "#DEB887",
    icon: "\u{1F4E6}",
  },
  {
    id: "storage-shoe-rack",
    name: "Обувница",
    category: "storage",
    width: 800,
    depth: 350,
    height: 1000,
    color: "#A0522D",
    icon: "\u{1F45F}",
  },
];

export default FURNITURE_CATALOG;
